package com.jabong.dap.common.constants.status

/**
 * All Different statuses of order
 */
object OrderStatus {

  val EXPORTABLE = 3
  val EXPORTED = 4
  val SHIPPED = 5
  val CLOSED = 6
  val CLARIFY_NOT_SHIPPED = 7
  val RETURN = 8
  val CANCELLED = 9
  val INVALID = 10
  val RETURN_DENIED = 11
  val REFUNDED = 12
  val CLARIFY_REFUND_FAILED = 14
  val CLARIFY_PAYMENT_ERROR = 15
  val CLARIFY_NOT_PAID = 16
  val MONEY_RECEIVED = 17
  val RETURN_PAYMENT_PENDING = 18
  val DECLINED = 23
  val PENDING = 24
  val CANCELLED_CC = 25
  val EXPORTABLE_CANCEL_CUST = 26
  val EXPORTED_CANCEL_CUST = 27
  val CANCELLED_WH = 28
  val CANCEL_PAYMENT_ERROR = 29
  val REFUNDED_AFTER_RETURNED = 32
  val REFUNDED_AFTER_CANCELLATION = 30
  val POTENTIAL_LIT = 33
  val FORWARD_LIT = 34
  val REFUNDED_AFTER_LIT = 35
  val POTENTIAL_CIR_LIT = 36
  val REVERSE_LIT = 37
  val RECEIVED_AT_ORIGIN = 38

  val INVALID_ARRAY = Array(INVALID)
  val CANCELLED_ARRAY = Array(REFUNDED_AFTER_CANCELLATION, CLARIFY_REFUND_FAILED, CLARIFY_PAYMENT_ERROR, CLARIFY_NOT_PAID, DECLINED, CANCELLED_CC, EXPORTABLE_CANCEL_CUST, EXPORTED_CANCEL_CUST, CANCELLED_WH)
  val RETURN_ARRAY = Array(RETURN, REFUNDED, REFUNDED_AFTER_RETURNED, REFUNDED_AFTER_LIT, POTENTIAL_CIR_LIT, POTENTIAL_LIT, REVERSE_LIT, RECEIVED_AT_ORIGIN)

  val SUCCESSFUL_ARRAY = Array(EXPORTABLE, EXPORTED, SHIPPED, CLOSED, CLARIFY_NOT_SHIPPED, RETURN_DENIED, MONEY_RECEIVED, PENDING, FORWARD_LIT)
}
