package com.jabong.dap.model.product.itr.variables

object ITR {

  /** ERP item_master view columns **/
  val BARCODE_EAN = "barcodeEan"
  val VENDOR_ITEM_NO = "vendorItemNo"
  val HEEL_HEIGHT = "heelHeight"
  val SLEEVE = "sleeve"
  val FIT = "fit"
  val NECK = "neck"
  val STYLE = "style"
  val MATERIAL = "material"
  val SUPPLIER_COLOR = "supplierColor"
  val STYLE_NAME = "styleName"
  val SUPPLIER_STYLE_CODE = "supplierStyleCode"
  val DISPATCH_LOCATION = "dispatchLocation"
  val PACKAGING = "packaging"
  val REPORTING_SUBCATEGORY = "reportingSubcategory"
  val REPORTING_CATEGORY = "reportingCategory"
  val BRAND_TYPE = "brandType"
  val ITEM_TYPE = "itemType"
  val SEASON = "season"
  val MRP_PRICE = "mrpPrice"
  val COLOR = "color"
  val SIZE = "size"
  val JABONG_CODE = "jabongCode"
  val PET_STYLE_CODE = "petStyleCode"
  val GENDER = "gender"
  val BRICK = "brick"
  val CLASS = "class"
  val FAMILY = "family"
  val SEGMENT = "segment"
  val BUSINESS_UNIT = "businessUnit"

  /** BOB columns **/
  val ID_CATALOG_SIMPLE = "idCatalogSimple"
  val SPECIAL_TO_DATE = "specialToDate"
  val SPECIAL_FROM_DATE = "specialFromDate"
  val SPECIAL_PRICE = "specialPrice"
  val SIMPLE_SKU = "simpleSku"
  val VISIBILITY = "visibility"
  val QUANTITY = "quantity"
  val ID_CATALOG_CONFIG = "idCatalogConfig"
  val PRODUCT_NAME = "productName"
  val ACTIVATED_AT = "activatedAt"
  val CONFIG_SKU = "configSku"
  val PRODUCT_URL = "productUrl"
  val SPECIAL_MARGIN = "specialMargin"
  val MARGIN = "margin"
  val MVP = "mvp"
  val PRICE_BAND = "priceBand"
  val BRAND_NAME = "brandName"
  val SUPPLIER_STATUS = "supplierStatus"
}
