package com.jabong.dap.common.constants.variables

/**
 * Created by jabong1145 on 18/6/15.
 */
object ACartVariables {

  val UID = "UID"
  val ACartStatus = "ACART_STATUS"
  val ACartSku1 = "ACART_PRICE_SKU1"
  val ACartSku2 = "ACART_PRICE_SKU2"
  val ACartPriceSku1 = "MAX_MRP_ACART_SKU1"
  val ACartPriceSku1Date = "MAX_MRP_ACART_SKU1_DATE"
  val ACartPriceSku1Mvp = "MAX_MRP_ACART_SKU1_MVP"
  val ACartPriceSku1Gender = "MAX_MRP_ACART_SKU1_GENDER"
  val ACartPriceSku1Brick = "MAX_MRP_ACART_SKU1_BRICK"
  val ACartPriceSku1Brand = "MAX_MRP_ACART_SKU1_BRAND"
  val ACartPriceSku1Category = "MAX_MRP_ACART_SKU1_CATEGORY"
  val ACartPriceSku1Color = "MAX_MRP_ACART_SKU1_COLOR"
  val ACartPriceSku1Price = "MAX_MRP_ACART_SKU1_PRICE"
  val ACartPriceSku1TodayPrice = "MAX_MRP_ACART_SKU1_TODAY_PRICE"
  val ACartPriceSku1Promotion30 = "MAX_MRP_ACART_SKU1_PROMOTION30"
  val ACartPriceSku2 = "MAX_MRP_ACART_SKU2"
  val ACartPriceSku2Date = "MAX_MRP_ACART_SKU2_DATE"
  val ACartPriceSku2Mvp = "MAX_MRP_ACART_SKU2_MVP"
  val ACartPriceSku2Gender = "MAX_MRP_ACART_SKU2_GENDER"
  val ACartPriceSku2Brick = "MAX_MRP_ACART_SKU2_BRICK"
  val ACartPriceSku2Brand = "MAX_MRP_ACART_SKU2_BRAND"
  val ACartPriceSku2Category = "MAX_MRP_ACART_SKU2_CATEGORY"
  val ACartPriceSku2Color = "MAX_MRP_ACART_SKU2_COLOR"
  val ACartPriceSku2Price = "MAX_MRP_ACART_SKU2_PRICE"
  val ACartPriceSku2TodayPrice = "MAX_MRP_ACART_SKU2_TODAY_PRICE"
  val ACartPriceSku2Promotion30 = "MAX_MRP_ACART_SKU2_PROMOTION30"

  val ACartStockSku1 = "LOW_STOCK_ACART_SKU1"
  val ACartStockSku1Date = "LOW_STOCK_ACART_SKU1_DATE"
  val ACartStockSku1Mvp = "LOW_STOCK_ACART_SKU1_MVP"
  val ACartStockSku1Gender = "LOW_STOCK_ACART_SKU1_GENDER"
  val ACartStockSku1Brick = "LOW_STOCK_ACART_SKU1_BRICK"
  val ACartStockSku1Brand = "LOW_STOCK_ACART_SKU1_BRAND"
  val ACartStockSku1Category = "LOW_STOCK_ACART_SKU1_CATEGORY"
  val ACartStockSku1Color = "LOW_STOCK_ACART_SKU1_COLOR"
  val ACartStockSku1Quantity = "LOW_STOCK_ACART_SKU1_QTY"
  val ACartStockSku1TodayQuantity = "LOW_STOCK_ACART_SKU1_TODAY_QTY"
  val ACartStockSku1Promotion30 = "LOW_STOCK_ACART_SKU1_PROMOTION30"
  val ACartStockSku2 = "LOW_STOCK_ACART_SKU2"
  val ACartStockSku2Date = "LOW_STOCK_ACART_SKU2_DATE"
  val ACartStockSku2Mvp = "LOW_STOCK_ACART_SKU2_MVP"
  val ACartStockSku2Gender = "LOW_STOCK_ACART_SKU2_GENDER"
  val ACartStockSku2Brick = "LOW_STOCK_ACART_SKU2_BRICK"
  val ACartStockSku2Brand = "LOW_STOCK_ACART_SKU2_BRAND"
  val ACartStockSku2Category = "LOW_STOCK_ACART_SKU2_CATEGORY"
  val ACartStockSku2Color = "LOW_STOCK_ACART_SKU2_COLOR"
  val ACartStockSku2Quantity = "LOW_STOCK_ACART_SKU2_QTY"
  val ACartStockSku2TodayQuantity = "LOW_STOCK_ACART_SKU2_TODAY_QTY"
  val ACartStockSku2Promotion30 = "LOW_STOCK_ACART_SKU2_PROMOTION30"

}
