package com.jabong.dap.common.constants.variables


object ACartVariables {


  val UID = "UID"
  val ACART_STATUS = "ACART_STATUS"
  val ACART_SKU1 = "ACART_PRICE_SKU1"
  val ACART_SKU2 = "ACART_PRICE_SKU2"
  val ACART_PRICE_SKU1 = "MAX_MRP_ACART_SKU1_"
  val ACART_PRICE_SKU1_DATE = "MAX_MRP_ACART_SKU1_DATE"
  val ACART_PRICE_SKU1_MVP = "MAX_MRP_ACART_SKU1_MVP"
  val ACART_PRICE_SKU1_GENDER = "MAX_MRP_ACART_SKU1_GENDER"
  val ACART_PRICE_SKU1_BRICK = "MAX_MRP_ACART_SKU1_BRICK"
  val ACART_PRICE_SKU1_BRAND = "MAX_MRP_ACART_SKU1_BRAND"
  val ACART_PRICE_SKU1_CATEGORY = "MAX_MRP_ACART_SKU1_CATEGORY"
  val ACART_PRICE_SKU1_COLOR = "MAX_MRP_ACART_SKU1_COLOR"
  val ACART_PRICE_SKU1_PRICE = "MAX_MRP_ACART_SKU1_PRICE"
  val ACART_PRICE_SKU1_TODAY_PRICE = "MAX_MRP_ACART_SKU1_TODAY_PRICE"
  val ACART_PRICE_SKU1_PROMOTION30 = "MAX_MRP_ACART_SKU1_PROMOTION30"
  val ACART_PRICE_SKU2 = "MAX_MRP_ACART_SKU2_"
  val ACART_PRICE_SKU2_DATE = "MAX_MRP_ACART_SKU2_DATE"
  val ACART_PRICE_SKU2_MVP = "MAX_MRP_ACART_SKU2_MVP"
  val ACART_PRICE_SKU2_GENDER = "MAX_MRP_ACART_SKU2_GENDER"
  val ACART_PRICE_SKU2_BRICK = "MAX_MRP_ACART_SKU2_BRICK"
  val ACART_PRICE_SKU2_BRAND = "MAX_MRP_ACART_SKU2_BRAND"
  val ACART_PRICE_SKU2_CATEGORY = "MAX_MRP_ACART_SKU2_CATEGORY"
  val ACART_PRICE_SKU2_COLOR = "MAX_MRP_ACART_SKU2_COLOR"
  val ACART_PRICE_SKU2_PRICE = "MAX_MRP_ACART_SKU2_PRICE"
  val ACART_PRICE_SKU2_TODAY_PRICE = "MAX_MRP_ACART_SKU2_TODAY_PRICE"
  val ACART_PRICE_SKU2_PROMOTION30 = "MAX_MRP_ACART_SKU2_PROMOTION30"


  val ACART_STOCK_SKU1 = "LOW_STOCK_ACART_SKU1"
  val ACART_STOCK_SKU1_DATE = "LOW_STOCK_ACART_SKU1_DATE"
  val ACART_STOCK_SKU1_MVP = "LOW_STOCK_ACART_SKU1_MVP"
  val ACART_STOCK_SKU1_GENDER = "LOW_STOCK_ACART_SKU1_GENDER"
  val ACART_STOCK_SKU1_BRICK = "LOW_STOCK_ACART_SKU1_BRICK"
  val ACART_STOCK_SKU1_BRAND = "LOW_STOCK_ACART_SKU1_BRAND"
  val ACART_STOCK_SKU1_CATEGORY = "LOW_STOCK_ACART_SKU1_CATEGORY"
  val ACART_STOCK_SKU1_COLOR = "LOW_STOCK_ACART_SKU1_COLOR"
  val ACART_STOCK_SKU1_QUANTITY = "LOW_STOCK_ACART_SKU1_QTY"
  val ACART_STOCK_SKU1_TODAY_QUANTITY = "LOW_STOCK_ACART_SKU1_TODAY_QTY"
  val ACART_STOCK_SKU1_PROMOTION30 = "LOW_STOCK_ACART_SKU1_PROMOTION30"
  val ACART_STOCK_SKU2 = "LOW_STOCK_ACART_SKU2"
  val ACART_STOCK_SKU2_DATE = "LOW_STOCK_ACART_SKU2_DATE"
  val ACART_STOCK_SKU2_MVP = "LOW_STOCK_ACART_SKU2_MVP"
  val ACART_STOCK_SKU2_GENDER = "LOW_STOCK_ACART_SKU2_GENDER"
  val ACART_STOCK_SKU2_BRICK = "LOW_STOCK_ACART_SKU2_BRICK"
  val ACART_STOCK_SKU2_BRAND = "LOW_STOCK_ACART_SKU2_BRAND"
  val ACART_STOCK_SKU2_CATEGORY = "LOW_STOCK_ACART_SKU2_CATEGORY"
  val ACART_STOCK_SKU2_COLOR = "LOW_STOCK_ACART_SKU2_COLOR"
  val ACART_STOCK_SKU2_QUANTITY = "LOW_STOCK_ACART_SKU2_QTY"
  val ACART_STOCK_SKU2_TODAY_QUANTITY = "LOW_STOCK_ACART_SKU2_TODAY_QTY"
  val ACART_STOCK_SKU2_PROMOTION30 = "LOW_STOCK_ACART_SKU2_PROMOTION30"


}