package com.jabong.dap.common.constants.variables

object CustomerVariables {

  //customer schema variables
  val ID_CUSTOMER = "id_customer"
  val EMAIL = "email"
  val INCREMENT_ID = "increment_id"
  val PREFIX = "prefix"
  val FIRST_NAME = "first_name"
  val MIDDLE_NAME = "middle_name"
  val LAST_NAME = "last_name"
  val BIRTHDAY = "birthday"
  val GENDER = "gender"
  val PHONE = "phone"
  val PASSWORD = "password"
  val RESTORE_PASSWORD_KEY = "restore_password_key"
  val IS_CONFIRMED = "is_confirmed"
  val EMAIL_VERIFIED_AT = "email_verified_at"
  val IS_MOBILE_VERIFIED = "is_mobile_verified"
  val MOBILE_VERIFIED_AT = "mobile_verified_at"
  val CONFIRMATION_KEY = "confirmation_key"
  val PAYMENT_REFERENCE_KEY = "payment_reference_key"
  val CREATED_AT = "created_at"
  val UPDATED_AT = "updated_at"
  val STORE_CREDITS_AVAILABLE = "store_credits_available"
  val STORE_CREDITS_VALIDITY = "store_credits_validity"
  val GIFTCARD_CREDITS_AVAILABLE = "giftcard_credits_available"
  val GIFTCARD_CREDITS_VALIDITY = "giftcard_credits_validity"
  val SESSION_COOKIE = "session_cookie"
  val LOGGED_IN = "logged_in"
  val REWARD_TYPE = "reward_type"
  val DOMAIN = "domain"
  val USER_DEVICE_TYPE = "user_device_type"
  val API_TOKEN = "api_token"
  val APP_LOGGED_IN = "app_logged_in"
  val ID_CUSTOMER_ADDITIONAL_INFO = "id_customer_additional_info"
  val FK_CUSTOMER = "fk_customer"
  val SOURCE = "source"
  val CITY = "city"
  val RELATIONSHIP_STATUS = "relationship_status"
  val ANNIVERSARY_DATE = "anniversary_date"
  val FACEBOOK_UID = "facebook_uid"
  val FACEBOOK_PIC_URL = "facebook_pic_url"
  val FACEBOOK_LINKED_DATE = "facebook_linked_date"
  val IS_VIA_FBCONNECT = "is_via_fbconnect"
  val CALCULATED_GENDER = "calculated_gender"
  val GOOGLE_UID = "google_uid"
  val GOOGLE_PIC_URL = "google_pic_url"
  val GOOGLE_LINKED_DATE = "google_linked_date"
  val IS_VIA_GOOGLECONNECT = "is_via_googleconnect"
  val GOOGLE_REFRESH_TOKEN = "google_refresh_token"
  val FB_ACCESS_TOKEN = "fb_access_token"
  val APP_VERSION = "app_version"
  val FK_CORPORATE_CUSTOMER = "fk_corporate_customer"
  val FK_REFERRAL_CODE = "fk_referral_code"
  val SMS_OPT = "sms_opt"

  //variables name
  val CUSTOMER_ALL_ORDER_TIMESLOT = "customer_all_order_timeslot"
  val CUSTOMER_PREFERRED_ORDER_TIMESLOT = "customer_preferred_order_timeslot"
  val ACC_REG_DATE = "acc_reg_date"
  val MAX_UPDATED_AT = "max_updated_at"
  val EMAIL_OPT_IN_STATUS = "email_opt_in_status"
  val FK_CUSTOMER_CPOT = "fk_customer_cpot"
  val NLS_UPDATED_AT = "nls_updated_at"
  val VERIFICATION_STATUS = "verification_status"
  val AGE = "age"

  //for renaming column name
  val NEW_ = "new_"

  val APP_FILTER = "_app_"
  val APP_TYPE ="app_type"
  val RESPONSYS_ID = "responsys_id"

}
