package com.jabong.dap.common.constants.variables

object CustomerVariables {

  //customer schema variables
  val ID_CUSTOMER = "id_customer"
  val EMAIL = "email"
  val INCREMENT_ID = "increment_id"
  val PREFIX = "prefix"
  val FIRST_NAME = "first_name"
  val MIDDLE_NAME = "middle_name"
  val LAST_NAME = "last_name"
  val BIRTHDAY = "birthday"
  val GENDER = "gender"
  val PHONE = "phone"
  val PASSWORD = "password"
  val RESTORE_PASSWORD_KEY = "restore_password_key"
  val IS_CONFIRMED = "is_confirmed"
  val EMAIL_VERIFIED_AT = "email_verified_at"
  val IS_MOBILE_VERIFIED = "is_mobile_verified"
  val MOBILE_VERIFIED_AT = "mobile_verified_at"
  val CONFIRMATION_KEY = "confirmation_key"
  val PAYMENT_REFERENCE_KEY = "payment_reference_key"
  val CREATED_AT = "created_at"
  val UPDATED_AT = "updated_at"
  val STORE_CREDITS_AVAILABLE = "store_credits_available"
  val STORE_CREDITS_VALIDITY = "store_credits_validity"
  val GIFTCARD_CREDITS_AVAILABLE = "giftcard_credits_available"
  val GIFTCARD_CREDITS_VALIDITY = "giftcard_credits_validity"
  val SESSION_COOKIE = "session_cookie"
  val LOGGED_IN = "logged_in"
  val REWARD_TYPE = "reward_type"
  val DOMAIN = "domain"
  val USER_DEVICE_TYPE = "user_device_type"
  val API_TOKEN = "api_token"
  val APP_LOGGED_IN = "app_logged_in"
  val ID_CUSTOMER_ADDITIONAL_INFO = "id_customer_additional_info"
  val FK_CUSTOMER = "fk_customer"
  val SOURCE = "source"
  val CITY = "city"
  val RELATIONSHIP_STATUS = "relationship_status"
  val ANNIVERSARY_DATE = "anniversary_date"
  val FACEBOOK_UID = "facebook_uid"
  val FACEBOOK_PIC_URL = "facebook_pic_url"
  val FACEBOOK_LINKED_DATE = "facebook_linked_date"
  val IS_VIA_FBCONNECT = "is_via_fbconnect"
  val CALCULATED_GENDER = "calculated_gender"
  val GOOGLE_UID = "google_uid"
  val GOOGLE_PIC_URL = "google_pic_url"
  val GOOGLE_LINKED_DATE = "google_linked_date"
  val IS_VIA_GOOGLECONNECT = "is_via_googleconnect"
  val GOOGLE_REFRESH_TOKEN = "google_refresh_token"
  val FB_ACCESS_TOKEN = "fb_access_token"
  val APP_VERSION = "app_version"
  val FK_CORPORATE_CUSTOMER = "fk_corporate_customer"
  val FK_REFERRAL_CODE = "fk_referral_code"
  val SMS_OPT = "sms_opt"
  val IS_PAYBACK_EARN = "is_payback_earn"
  val ZONE = "ZONE"
  val TIER1 = "TIER1"

  //variables name
  val CUSTOMER_ALL_ORDER_TIMESLOT = "customer_all_order_timeslot"
  val CUSTOMER_PREFERRED_ORDER_TIMESLOT = "customer_preferred_order_timeslot"
  val LAST_UPDATED_AT = "last_updated_at"
  val NLS_UPDATED_AT = "nls_updated_at"

  val APP_FILTER = "_app_"
  val APP_TYPE = "app_type"
  val PREFERRED_BRAND = "preferred_brand"

  val CUSTOMER_ID = "customer_id"
  val ORDER_0 = "order_0"
  val ORDER_1 = "order_1"
  val ORDER_2 = "order_2"
  val ORDER_3 = "order_3"
  val ORDER_4 = "order_4"
  val ORDER_5 = "order_5"
  val ORDER_6 = "order_6"
  val ORDER_7 = "order_7"
  val ORDER_8 = "order_8"
  val ORDER_9 = "order_9"
  val ORDER_10 = "order_10"
  val ORDER_11 = "order_11"
  val PREFERRED_ORDER_TIMESLOT = "preferred_order_timeslot"

  val OPEN_0 = "open_0"
  val OPEN_1 = "open_1"
  val OPEN_2 = "open_2"
  val OPEN_3 = "open_3"
  val OPEN_4 = "open_4"
  val OPEN_5 = "open_5"
  val OPEN_6 = "open_6"
  val OPEN_7 = "open_7"
  val OPEN_8 = "open_8"
  val OPEN_9 = "open_9"
  val OPEN_10 = "open_10"
  val OPEN_11 = "open_11"
  val CLICK_0 = "click_0"
  val CLICK_1 = "click_1"
  val CLICK_2 = "click_2"
  val CLICK_3 = "click_3"
  val CLICK_4 = "click_4"
  val CLICK_5 = "click_5"
  val CLICK_6 = "click_6"
  val CLICK_7 = "click_7"
  val CLICK_8 = "click_8"
  val CLICK_9 = "click_9"
  val CLICK_10 = "click_10"
  val CLICK_11 = "click_11"
  val PREFERRED_OPEN_TIMESLOT = "preferred_open_timeslot"
  val PREFERRED_CLICK_TIMESLOT = "preferred_click_timeslot"

  val EVENT_CAPTURED_DT = "EVENT_CAPTURED_DT"
  val ID_CUSTOMER_SESSION = "id_customer_session"

  //Ad4PushVariables
  var DEVICE_ID = "device_id"
  var UDID = "UDID"
  var TOKEN = "token"
  var OPENCOUNT = "opencount"
  var FIRSTOPEN = "firstopen"
  var LASTOPEN = "lastopen"
  var MODEL = "model"
  var VERSION = "version"
  var LANGUAGE = "language"
  var BUNDLEVERSION = "bundleversion"
  var LAT = "lat"
  var LON = "lon"
  var ALTITUDE = "altitude"
  var GEOLOCATION_CREATED = "geolocationCreated"
  var VERSIONSDK = "versionsdk"
  var FEEDBACK = "feedback"
  var TIME_ZONE = "time_zone"
  var SYSTEM_OPTIN_NOTIFS = "system_optin_notifs"
  var ENABLED_NOTIFS = "enabled_notifs"
  var ENABLED_INAPPS = "enabled_inapps"
  var RANDOMID = "randomId"
  var COUNTRYCODE = "countryCode"
  var AGGREGATED_NUMBER_OF_PURCHASES = "aggregatedNumberOfPurchases"
  var HAS_SHARED_PRODUCT = "hasSharedProduct"
  var LAST_ABANDONED_CART_DATE = "lastAbandonedCartDate"
  var LAST_ABANDONED_CART_PRODUCT = "lastAbandonedCartProduct"
  var LASTORDERDATE = "lastOrderDate"
  var LAST_SEARCH = "lastSearch"
  var LAST_SEARCH_DATE = "lastSearchDate"
  var LEAD = "lead"
  var LOGIN_USER_ID = "loginUserID"
  var MOST_VISITED_CATEGORY = "mostVisitedCategory"
  var ORDER_STATUS = "orderStatus"
  var PURCHASE = "purchase"
  var REGISTRATION = "registration"
  var STATUS_IN_APP = "statusInApp"
  var WISHLIST_STATUS = "wishlistStatus"
  var WISHLIST_ADD = "wishlist_add"
  var SHOP_COUNTRY = "shopCountry"
  var AMOUNT_BASKET = "amount_basket"
  var CART = "cart"
  var SPECIFIC_CATEGORY_VISIT_COUNT = "specific_category_visit_count"
  var USER_NAME = "userName"
  var LAST_VIEWED_CATEGORY = "LastViewedCategory"
  var MAX_VISITED_CATEGORY = "maxVisitedCategory"
  var MOST_VISITED_COUNTS = "mostVisitedCounts"

  //Extra fields for 515
  var IDFA = "IDFA"
  var LAST_ORDER_DATE = "last_order_date" //for 515 lastOrderDate coming 0000-00-00 00:00:00
  var SEARCH_DATE = "search_date" //search_date coming as 0000-00-00 00:00:00 where as lastSearchDate coming as 2020-07-27 00:00:00
  var WISHLIST_PRODUCTS_COUNT = "wishlist_products_count"
  var RATED = "rated"

  //Devices Reactions CSV fields
  val MESSAGE_ID = "message_id"
  val CAMPAIGN_ID = "campaign_id"
  val BOUNCE = "bounce"
  val REACTION = "reaction"

  //DeviceReaction variables Full
  val LAST_CLICK_DATE = "last_click_date"
  val CLICK_15 = "click_15"
  val CLICK_30 = "click_30"
  val CLICK_LIFETIME = "click_lifetime"
  val CLICK_MONDAY = "click_monday"
  val CLICK_TUESDAY = "click_tuesday"
  val CLICK_WEDNESDAY = "click_wednesday"
  val CLICK_THURSDAY = "click_thursday"
  val CLICK_FRIDAY = "click_friday"
  val CLICK_SATURDAY = "click_saturday"
  val CLICK_SUNDAY = "click_sunday"
  val CLICKED_TWICE = "clicked_twice"
  val MOST_CLICK_DAY = "most_click_day"

  //working constants
  val EFFECTIVE_7_DAYS = "effective_7_days"
  val EFFECTIVE_15_DAYS = "effective_15_days"
  val EFFECTIVE_30_DAYS = "effective_30_days"
  val MONDAY = "monday"
  val TUESDAY = "tuesday"
  val WEDNESDAY = "wednesday"
  val THURSDAY = "thursday"
  val FRIDAY = "friday"
  val SATURDAY = "saturday"
  val SUNDAY = "sunday"
  val CLICK_ = "click_"

  // DeviceReaction variables Incremental
  val CLICKED_TODAY = "clicked_today"
  val CLICKED_7_DAYS = "clicked_7_days"
  val CLICKED_15_DAYS = "clicked_15_days"
  val CLICKED_30_DAYS = "clicked_30_days"

  //CustomerProductShortlistVariables
  val ID_CUSTOMER_PRODUCT_SHORTLIST = "id_customer_product_shortlist"
  val USER_SHORTLIST_KEY = "user_shortlist_key"
  val USER_TOKEN = "user_token"
  val SKU = "sku"
  val SIMPLE_SKU = "simpleSku"
  val EXTRA_DATA = "extra_data"
  val STOCK_WHEN_REMOVED = "stock_when_removed"
  val CUSTOMER_SOURCE = "customer_source"
  val REMOVED_AT = "removed_at"
  val PRICE = "price"
  val AVERAGE_PRICE = "average_price"
  val SKU_SIMPLE = "skuSimple"
  val SPECIAL_PRICE = "specialPrice"

  //FeedFile variables
  val EMAIL_SUBSCRIPTION_STATUS = "email_subscription_status"
  val CUR_NL_STATUS = "cur_nl_status"
  val PROCESSED_DATE = "processed_date"
  val NET_ORDERS = "net_orders"
  val REG_DATE = "reg_date"
  val UID = "uid"
  val MOBILE_PERMISSION_STATUS = "mobile_permission_status"
  val COUNTRY = "country"
  val MOBILE = "mobile"
}
