package com.jabong.dap.common.constants.variables

/**
 * Created by jabong1145 on 22/6/15.
 */
object CustomerVariables {

  //customer schema variables
  val IdCustomer = "id_customer"
  val Email = "email"
  val IncrementId = "increment_id"
  val Prefix = "prefix"
  val FirstName = "first_name"
  val MiddleName = "middle_name"
  val LastName = "last_name"
  val Birthday = "birthday"
  val Gender = "gender"
  val Phone = "phone"
  val Password = "password"
  val RestorePasswordKey = "restore_password_key"
  val IsConfirmed = "is_confirmed"
  val EmailVerifiedAt = "email_verified_at"
  val IsMobileVerified = "is_mobile_verified"
  val MobileVerified_at = "mobile_verified_at"
  val ConfirmationKey = "confirmation_key"
  val PaymentReferenceKey = "payment_reference_key"
  val CreatedAt = "created_at"
  val UpdatedAt = "updated_at"
  val StoreCreditsAvailable = "store_credits_available"
  val StoreCreditsValidity = "store_credits_validity"
  val GiftcardCreditsAvailable = "giftcard_credits_available"
  val GiftcardCreditsValidity = "giftcard_credits_validity"
  val SessionCookie = "session_cookie"
  val LoggedIn = "logged_in"
  val RewardType = "reward_type"
  val Domain = "domain"
  val UserDeviceType = "user_device_type"
  val ApiToken = "api_token"
  val AppLoggedIn = "app_logged_in"
  val IdCustomerAdditionalInfo = "id_customer_additional_info"
  val CustomerForeignKey ="fk_customer"
  val Source = "source"
  val City = "city"
  val RelationshipStatus = "relationship_status"
  val AnniversaryDate = "anniversary_date"
  val FacebookUid = "facebook_uid"
  val FacebookPicUrl = "facebook_pic_url"
  val FacebookLinkedDate = "facebook_linked_date"
  val IsViaFbconnect = "is_via_fbconnect"
  val CalculatedGender = "calculated_gender"
  val GoogleUid = "google_uid"
  val GooglePicUrl = "google_pic_url"
  val GoogleLinkedDate = "google_linked_date"
  val IsViaGoogleconnect = "is_via_googleconnect"
  val GoogleRefreshToken = "google_refresh_token"
  val FbAccessToken = "fb_access_token"
  val AppVersion = "app_version"
  val FkCorporateCustomer = "fk_corporate_customer"
  val FkReferralCode = "fk_referral_code"
  val SmsOpt = "sms_opt"

  //variables name
  val CustomerAllOrderTimeslot = "customer_all_order_timeslot"
  val CustomerPreferredOrderTimeslot = "customer_preferred_order_timeslot"
  val AccRegDate = "acc_reg_date"
  val MaxUpdatedAt = "max_updated_at"
  val EmailOptInStatus ="email_opt_in_status"
  val FkCustomerCPOT = "fk_customer_cpot"
  val NlsUpdatedAt = "nls_updated_at"


}
