package com.jabong.dap.common.constants.variables

/**
 * Created by mubarak on 4/9/15.
 */
object DNDVariables {

  var EVENT_UUID = "EVENT_UUID"
  var EVENT_TYPE_ID = "EVENT_TYPE_ID"
  var ACCOUNT_ID = "ACCOUNT_ID"
  var LIST_ID = "LIST_ID"
  var RIID = "RIID"
  var EVENT_CAPTURED_DT = "EVENT_CAPTURED_DT"
  var EVENT_STORED_DT = "EVENT_STORED_DT"
  var CAMPAIGN_ID = "CAMPAIGN_ID"
  var LAUNCH_ID = "LAUNCH_ID"
  var PROGRAM_ID = "PROGRAM_ID"
  var AGGREGATOR_ID = "AGGREGATOR_ID"
  var COUNTRY_CODE = "COUNTRY_CODE"
  var MOBILE_CODE = "MOBILE_CODE"
  var MOBILE_NUMBER = "MOBILE_NUMBER"
  var MOBILE_CHANNEL = "MOBILE_CHANNEL"
  var MOBILE_CARRIER = "MOBILE_CARRIER"
  var SMS_SENT_UUID = "SMS_SENT_UUID"
  var DELIVERED_FLAG = "DELIVERED_FLAG"
  var AGGREGATOR_MESSAGE_ID = "AGGREGATOR_MESSAGE_ID"
  var AGGREGATOR_MESSAGE_SUBID = "AGGREGATOR_MESSAGE_SUBID"
  var AGGREGATOR_STATUS_CODE = "AGGREGATOR_STATUS_CODE"
  var AGGREGATOR_STATUS_DESC = "AGGREGATOR_STATUS_DESC"
  var PROCESSED_DATE = "PROCESSED_DATE"

}
