package com.jabong.dap.common.constants.variables

/**
 * Created by mubarak on 4/9/15.
 */
object DNDVariables {

  val EVENT_UUID = "EVENT_UUID"
  val EVENT_TYPE_ID = "EVENT_TYPE_ID"
  val ACCOUNT_ID = "ACCOUNT_ID"
  val LIST_ID = "LIST_ID"
  val RIID = "RIID"
  val EVENT_CAPTURED_DT = "EVENT_CAPTURED_DT"
  val EVENT_STORED_DT = "EVENT_STORED_DT"
  val CAMPAIGN_ID = "CAMPAIGN_ID"
  val LAUNCH_ID = "LAUNCH_ID"
  val PROGRAM_ID = "PROGRAM_ID"
  val AGGREGATOR_ID = "AGGREGATOR_ID"
  val COUNTRY_CODE = "COUNTRY_CODE"
  val MOBILE_CODE = "MOBILE_CODE"
  val MOBILE_NUMBER = "MOBILE_NUMBER"
  val MOBILE_CHANNEL = "MOBILE_CHANNEL"
  val MOBILE_CARRIER = "MOBILE_CARRIER"
  val SMS_SENT_UUID = "SMS_SENT_UUID"
  val DELIVERED_FLAG = "DELIVERED_FLAG"
  val AGGREGATOR_MESSAGE_ID = "AGGREGATOR_MESSAGE_ID"
  val AGGREGATOR_MESSAGE_SUBID = "AGGREGATOR_MESSAGE_SUBID"
  val AGGREGATOR_STATUS_CODE = "AGGREGATOR_STATUS_CODE"
  val AGGREGATOR_STATUS_DESC = "AGGREGATOR_STATUS_DESC"
  val PROCESSED_DATE = "PROCESSED_DATE"

}
