package com.jabong.dap.common.constants.variables

/**
 * Created by raghu on 1/7/15.
 */
object SalesOrderVariables {

  //SalesOrder schema variables
  val ID_SALES_ORDER = "id_sales_order"
  val FK_SALES_ORDER_ADDRESS_BILLING = "fk_sales_order_address_billing"
  val FK_SALES_ORDER_ADDRESS_SHIPPING = "fk_sales_order_address_shipping"
  val FK_CUSTOMER = "fk_customer"
  val CUSTOMER_FIRST_NAME = "customer_first_name"
  val CUSTOMER_LAST_NAME = "customer_last_name"
  val CUSTOMER_EMAIL = "customer_email"
  val ORDER_NR = "order_nr"
  val CUSTOMER_SESSION_ID = "customer_session_id"
  val STORE_ID = "store_id"
  val GRAND_TOTAL = "grand_total"
  val TAX_AMOUNT = "tax_amount"
  val SHIPPING_AMOUNT = "shipping_amount"
  val SHIPPING_METHOD = "shipping_method"
  val COUPON_CODE = "coupon_code"
  val PAYMENT_METHOD = "payment_method"
  val CREATED_AT = "created_at"
  val UPDATED_AT = "updated_at"
  val FK_SHIPPING_CARRIER = "fk_shipping_carrier"
  val TRACKING_URL = "tracking_url"
  val OTRS_TICKET = "otrs_ticket"
  val FK_SALES_ORDER_PROCESS = "fk_sales_order_process"
  val SHIPPING_DISCOUNT_AMOUNT = "shipping_discount_amount"
  val IP = "ip"
  val INVOICE_FILE = "invoice_file"
  val INVOICE_NR = "invoice_nr"
  val IS_RECURRING = "is_recurring"
  val CCAVENUE_ORDER_NUMBER = "ccavenue_order_number"
  val COD_CHARGE = "cod_charge"
  val RETRIAL = "retrial"
  val ID_SALES_ORDER_ADDITIONAL_INFO = "id_sales_order_additional_info"
  val FK_SALES_ORDER = "fk_sales_order"
  val FK_AFFILIATE_PARTNER = "fk_affiliate_partner"
  val FK_SHIPPING_PARTNER_AGENT = "fk_shipping_partner_agent"
  val DOMAIN = "domain"
  val USER_DEVICE_TYPE = "user_device_type"
  val SHIPMENT_DELAY_DAYS = "shipment_delay_days"
  val MOBILE_VERIFICATION = "mobile_verification"
  val ADDRESS_MISMATCH = "address_mismatch"
  val EARN_METHOD = "earn_method"
  val PARENT_ORDER_ID = "parent_order_id"
  val UTM_CAMPAIGN = "utm_campaign"
  val REWARD_POINTS = "reward_points"
  val APP_VERSION = "app_version"
  val FK_CORPORATE_CUSTOMER = "fk_corporate_customer"
  val CORPORATE_CURRENCY_VALUE = "corporate_currency_value"
  val CORPORATE_TRANSACTION_ID = "corporate_transaction_id"
  val DEVICE_ID = "device_id"
  val ID_SALES_ORDER_GIFT_WRAP = "id_sales_order_gift_wrap"
  val GW_RECIPIENT_EMAIL = "gw_recipient_email"
  val GW_RECIPIENT_NAME = "gw_recipient_name"
  val GW_MESSAGE = "gw_message"
  val GW_SENDER_NAME = "gw_sender_name"
  val GW_AMOUNT = "gw_amount"
  val GW_GIFTCARD_CREDIT = "gw_giftcard_credit"
  val GW_STORE_CREDIT = "gw_store_credit"
  val GW_PAID_PRICE = "gw_paid_price"
  val GW_PAYBACK_CREDIT = "gw_payback_credit"
  val OCCASION = "occasion"

  //variables name
  val SO_CREATED_AT = "so_created_at"
  val SO_UPDATED_AT = "so_updated_at"
  val COUPON_SCORE = "coupon_score"
  val DAYS_SINCE_LAST_ORDER = "days_since_last_order"
  val FIRST_ORDER_DATE = "first_order_date"
  val ORDERS_COUNT = "orders_count"

  val NEW_ = "new_"
}
