package com.jabong.dap.common.constants.variables

/**
 * Created by mubarak on 6/7/15.
 * Sales order item variables
 */
object SalesOrderItemVariables {
  val ID_SALES_ORDER_ITEM = "id_sales_order_item"
  val FK_SALES_ORDER = "fk_sales_order"
  val FK_SALES_ORDER_ITEM_STATUS = "fk_sales_order_item_status"
  val CREATED_AT = "created_at"
  val UPDATED_AT = "updated_at"
  val ORDERS_COUNT = "orders_count"
  val PAID_PRICE = "paid_price"
  val GIFTCARD_CREDITS_VALUE = "giftcard_credits_value"
  val STORE_CREDITS_VALUE = "store_credits_value"
  val PAYBACK_CREDITS_VALUE = "payback_credits_value"
  val FILTER_APP = "domain ='android' or domain = 'ios' or domain ='windows'"
  val FILTER_WEB = "domain ='w'"
  val FILTER_MWEB = "domain ='m'"
  val APP = "/app/"
  val WEB = "/web/"
  val MOBILE_WEB = "/mobile_web/"
  val UNIT_PRICE = "unit_price"
  val SALES_ORDER_ITEM_STATUS = "fk_sales_order_item_status"
  val REVENUE = "revenue"
  val REVENUE_APP = "revenue_app"
  val REVENUE_WEB = "revenue_web"
  val REVENUE_MWEB = "revenue_mweb"
  val ORDERS_COUNT_APP = "orders_count_app"
  val ORDERS_COUNT_WEB = "orders_count_web"
  val ORDERS_COUNT_MWEB = "orders_count_mweb"
  val FILTER_SUCCESSFUL_ORDERS = "fk_sales_order_item_status = 3 or fk_sales_order_item_status = 4 or fk_sales_order_item_status = 5 or fk_sales_order_item_status = 6 or fk_sales_order_item_status = 7 or fk_sales_order_item_status = 11 or fk_sales_order_item_status = 17 or fk_sales_order_item_status = 24 or fk_sales_order_item_status = 33 or fk_sales_order_item_status = 34"
  val ORDERS_COUNT_SUCCESSFUL = "orders_count_successful"
  val FAV_BRAND = "fav_brand"

  val REVENUE_APP_LIFE = "revenue_app_life"
  val REVENUE_WEB_LIFE = "revenue_web_life"
  val REVENUE_MWEB_LIFE = "revenue_mweb_life"
  val ORDERS_COUNT_APP_LIFE = "orders_count_app_life"
  val ORDERS_COUNT_WEB_LIFE = "orders_count_web_life"
  val ORDERS_COUNT_MWEB_LIFE = "orders_count_mweb_life"
  val ORDERS_COUNT_LIFE = "oredrs_count_life"

  val REVENUE_7 = "revenue_7"
  val REVENUE_30 = "revenue_30"
  val REVENUE_90 = "revenue_90"
  val REVENUE_LIFE = "revenue_life"
  val REVENUE_APP_7 = "revenue_app_7"
  val REVENUE_APP_30 = "revenue_app_30"
  val REVENUE_APP_90 = "revenue_app_90"
  val REVENUE_WEB_7 = "revenue_web_7"
  val REVENUE_WEB_30 = "revenue_web_30"
  val REVENUE_WEB_90 = "revenue_web_90"
  val REVENUE_MWEB_7 = "revenue_mweb_7"
  val REVENUE_MWEB_30 = "revenue_mweb_30"
  val REVENUE_MWEB_90 = "revenue_mweb_90"
  val SUCCESSFUL_ORDERS = "successful_orders"
  val ORDERS_COUNT_7 = "orders_count_7"
  val ORDERS_COUNT_30 = "orders_count_30"
  val ORDERS_COUNT_90 = "orders_count_90"
  val ORDERS_COUNT_APP_7 = "orders_count_app_7"
  val ORDERS_COUNT_APP_30 = "orders_count_app_30"
  val ORDERS_COUNT_APP_90 = "orders_count_app_90"
  val ORDERS_COUNT_WEB_7 = "orders_count_web_7"
  val ORDERS_COUNT_WEB_30 = "orders_count_web_30"
  val ORDERS_COUNT_WEB_90 = "orders_count_web_90"
  val ORDERS_COUNT_MWEB_7 = "orders_count_mweb_7"
  val ORDERS_COUNT_MWEB_30 = "orders_count_mweb_30"
  val ORDERS_COUNT_MWEB_90 = "orders_count_mweb_90"

  val FK_SALES_MERCHANT_ORDER = "fk_sales_merchant_order"
  val FK_SALES_ORDER_ITEM_SHIPMENT = "fk_sales_order_item_shipment"
  val FK_SALES_ORDER_ITEM_MERCHANT = "fk_sales_order_item_merchant"
  val FK_MARKETPLACE_MERCHANT = "fk_marketplace_merchant"
  val FK_SALES_ORDER_ADDRESS_WAREHOUSE = "fk_sales_order_address_warehouse"
  val TAX_AMOUNT = "tax_amount"
  val COUPON_MONEY_VALUE = "coupon_money_value"
  val COUPON_PERCENT = "coupon_percent"
  val COUPON_REFUNDABLE = "coupon_refundable"
  val COUPON_CATEGORY = "coupon_category"
  val NAME = "name"
  val SKU = "sku"
  val WEIGHT = "weight"
  val ADDITIONAL_TEXT = "additional_text"
  val LAST_STATUS_CHANGE = "last_status_change"
  val AMOUNT_PAID = "amount_paid"
  val REFUNDED_MONEY = "refunded_money"
  val REFUNDED_VOUCHER = "refunded_voucher"
  val TAX_PERCENT = "tax_percent"
  val ORIGINAL_UNIT_PRICE = "original_unit_price"
  val CART_RULE_DISCOUNT = "cart_rule_discount"
  val CART_RULE_DISPLAY_NAMES = "cart_rule_display_names"
  val FK_CATALOG_SHIPMENT_TYPE = "fk_catalog_shipment_type"
  val IS_RESERVED = "is_reserved"
  val DELIVERY_TIME = "delivery_time"
  val DISPATCH_TIME = "dispatch_time"
  val BUNDLE_DISCOUNT = "bundle_discount"
  val FK_SKU_BUNDLE = "fk_sku_bundle"
  val IS_FREEBIE = "is_freebie"
  val SHIPPING_CHARGE = "shipping_charge"
  val ID_SALES_ORDER_ITEM_ADDITIONAL_INFO = "id_sales_order_item_additional_info"
  val FK_SALES_ORDER_ITEM = "fk_sales_order_item"
  val IS_CANCELABLE = "is_cancelable"
  val IS_RETURNABLE = "is_returnable"
  val IS_COD = "is_cod"
  val NOT_BUYABLE = "not_buyable"
  val PROCESSING_TIME = "processing_time"
  val EXPECTED_DISPATCH_DATE = "expected_dispatch_date"
  val EXPECTED_DELIVERY_DATE = "expected_delivery_date"
  val IS_DATE_CHANGED = "is_date_changed"
  val PACK_ID = "pack_id"
  val BUNDLE_PACK_IDENTIFIER = "bundle_pack_identifier"
  val PACK_QTY = "pack_qty"
  val MARGIN = "margin"
  val SHIPPING_LIABILITY = "shipping_liability"
  val DISPATCH_LOCATION = "dispatch_location"
  val HOLIDAY_COUNT = "holiday_count"
  val IS_GIFT_WRAPPED = "is_gift_wrapped"
  val MODE_OF_DISCOUNT_AMOUNT = "mode_of_discount_amount"
  val MODE_OF_PAYMENT_AMOUNT = "mode_of_payment_amount"
  val DISCOUNT_CAP = "discount_cap"
  val VAT_AMOUNT = "vat_amount"
  val IS_VAT_CHARGED = "is_vat_charged"
  val FK_CATALOG_ATTRIBUTE_OPTION_GLOBAL_ORDER_TYPE = "fk_catalog_attribute_option_global_order_type"
  val PRE_ORDER_ITEM_DISPATCH_DATE = "pre_order_item_dispatch_date"
  val PRE_ORDER_ITEM_CAMPAIGN_NAME = "pre_order_item_campaign_name"
  val IS_PAYBACK_REFUNDED = "is_payback_refunded"
  val IS_CUSTOMIZED = "is_customized"
  val CUSTOMIZATION_COST = "customization_cost"
  val PAYBACK_EARN_VALUE = "payback_earn_value"
  val REWARD_POINTS = "reward_points"
  val PROCESSED_BITMAP = "processed_bitmap"
  val EXPECTED_SHIPPING_PARTNER = "expected_shipping_partner"
  val IS_MULTIPLE_SHIPMENTS = "is_multiple_shipments"
  val CORPORATE_CURRENCY_VALUE = "corporate_currency_value"
  val ORIGINAL_SHIPPING_CHARGE = "original_shipping_charge"

  val COUNT_OF_RET_ORDERS = "COUNT_OF_RET_ORDERS"
  val COUNT_OF_CNCLD_ORDERS = "COUNT_OF_CNCLD_ORDERS"
  val COUNT_OF_INVLD_ORDERS = "COUNT_OF_INVLD_ORDERS"
  val GROSS_ORDERS = "GROSS_ORDERS"
}
