package com.jabong.dap.model.clickstream.variables

/**
 * Created by Divya
 */
object ClickstreamFields {

  var ID = "id"
  var BROWSER_ID = "browserid"
  var USER_ID = "userid"
  var IP = "ip"
  var CHANNEL = "channel"
  var PAGETS = "pagets"
  var CATEGORIES = "categories"
  var URL = "url"
  var PAGETYPE = "pagetype"
  var REFERRER = "referrer"
  var BRAND = "brand"
  var SESSIONID = "sessionid"
  var AJAX = "ajax"
  var FORMULA = "formula"
  var PRODUCT_SKU = "productsku"
  var IMPRESSION = "impressions"
  var VOUCHER_CODE = "vouchercode"
  var VOUCHER_FAILED_REASON = "voucherfailedreason"
  var CART_SKU = "cartskus"
  var ORDER = "corder"
  var POSITION = "position"
  var DOMAIN = "domain"
  var DEVICE = "device"
  var SUGGESTIONS = "suggestions"
  var USER_AGENT = "useragent"
  var USER_MATCH = "usermatch"
  var APP_STORE_EMAIL = "appstoreemail"
  var INTERNET_CONNECTION = "internetconnection"
  var MOBILE_OS = "mobileos"
  var ORDER_ID = "id"
  var ORDER_TOTAL_PRICE = "totalprice"
  var ORDER_PAYMENT_MODE = "paymentmode"
  var ORDER_FIRST_ORDER = "firstorder"
  var ORDER_ITEMS = "products"
  var ORDER_ITEM_SKU = "sku"
  var ORDER_ITEM_PRICE = "price"
  var IMPRESSION_SKU = "sku"
  var SKU_ROW = "srow"
  var SKU_COLUMN = "scol"
  var PRODUCT_SKU_POSITION = "position"
  var TYPED_TERM = "typedterm"
  var CLICKED_TERM = "clickedterm"
  var CLICKED_TERM_RANK = "rank"
  var SUGGESTIONS_LIST = "suggestionslist"
  var ACTUAL_VISITID = "actualvisitid"
  var VISITTS = "visitts"
}
